### ISSUE TITLE
wizard does not work in mac safari 15.3

### ISSUE THREAD

**Issue by VladimirRakovich** [laravel-filament/filament#12975]
### Package

filament/filament

### Package Version

v3.2.83

### Laravel Version

v11.8.0

### Livewire Version

v3.4.10

### PHP Version

php 8.3.0

### Problem description

Wizard does not work in the demo application in Mac Safari 15.3.
There is an error in the browser console
`this.getSteps().at is not a function. (In 'this.getSteps().at(0)', 'this.getSteps().at' is undefined)`

possible solution here https://www.answeroverflow.com/m/1127561179766726748

### Expected behavior

Wizard works

### Steps to reproduce

Open https://demo.filamentphp.com/shop/orders/create in mac safari

### Reproduction repository

https://github.com/filamentphp/demo

**Comment by sebapastore** [comment]
Just to add more info, it's working OK in Safari 17.4.1 .

**Comment by danharrin** [comment]
Can someone PR the solution as suggested in the Answer Overflow thread please?

**Comment by sebapastore** [comment]
According to the official Safari release notes, `Array.prototype.at` was added in [15.4 release](https://developer.apple.com/documentation/safari-release-notes/safari-15_4-release-notes). Additionally, [this support page](https://support.apple.com/en-us/103193), indicates that Safari 15.4 is available for macOS Catalina and newer versions. This information is consistent with the issue, which describes using Safari 15.3. Therefore, users running Catalina should be able to update Safari to 15.4.

The macOS version prior to Catalina is Mojave, and its last update, according to official release, was [version 10.14.6](https://developer.apple.com/documentation/macos-release-notes/macos-mojave-10_14_6-release-notes). And according to [this support page](https://support.apple.com/en-us/106416), this update has been available since September 2019.. So I think it is not recommended to continue using Mojave.

This is just my perspective, and I understand that others may have different views or reasons for using specific software versions.

**Comment by sebapastore** [comment]
If, knowing these dates and versions, it is considered that Safari 15.3 should be supported, then I can prepare a PR.

**Comment by danharrin** [comment]
I'm going to close this as Safari <= 15.3 appears to have ~0.3% usage

https://caniuse.com/usage-table
