### ISSUE TITLE
Livewire.interceptMessage is not a function` error in Filament 5.1 with Livewire 4

### ISSUE THREAD

**Issue by theMelfix** [laravel-filament/filament#19070]
### Package

filament/filament

### Package Version

5.1.0

### Laravel Version

12.x

### Livewire Version

v4.0.3

### PHP Version

8.5

### Problem description

 ```js                                                                                                                             
  Uncaught TypeError: Livewire.interceptMessage is not a function at schemas.js?v=5.1.0.0:1:2067       

Cause:                                                                                                                            
  schemas.js calls Livewire.interceptMessage() which was a Livewire 3 API and does not exist in Livewire 4.                         
                                                                                                                                    
  Affected files:                                                                                                                   
  - filament/schemas/schemas.js                                                                                                     
  - filament/notifications/notifications.js                                                                                         
  - filament/support/support.js      

### Expected behavior

Filament 5.1 should work correctly with Livewire 4.0+ without JavaScript errors.                                                  
                                                                                                                                    
  Modal actions (Edit, Delete, Create) in tables and relation managers should open properly when clicked.                           
                                                                                                                                    
  The JavaScript assets should use Livewire 4 compatible APIs instead of deprecated Livewire 3 methods like `interceptMessage()`. 

### Steps to reproduce

  1. Create a new Laravel 12 project                                                                                                
  2. Install Filament 5.1:                                                                                                          
     ```bash                                                                                                                        
     composer require filament/filament:"^5.0"                                                                                      
     php artisan filament:install --panels                                                                                          
  3. Create any resource with a table:                                                                                              
  php artisan make:filament-resource Post --generate                                                                                
  4. Open browser console (F12) and navigate to the resource list page                                                              
  5. See error: Uncaught TypeError: Livewire.interceptMessage is not a function                                                     
  6. Try clicking Edit or Delete action on any row - modal does not open                                                            
                                                                                                                                    
  Minimal reproduction:                                                                                                             
  The error occurs immediately on any Filament page load because schemas.js executes:                                               
  Livewire.interceptMessage(({message: i, onSuccess: e}) => { ... })                                                                
                                                                                                                                    
  This method does not exist in Livewire 4.   

### Reproduction repository (issue will be closed if this is not valid)

https://github.com/theMelfix/filament-livewire4-bug/

### Relevant log output

```shell
support.js?v=5.1.0.0:25 Uncaught TypeError: Livewire.interceptMessage is not a function
    at HTMLDocument.<anonymous> (support.js?v=5.1.0.0:25:13898)
    at dispatch (livewire.js?id=0f6341c0:340:12)
    at Object.start2 [as start] (livewire.js?id=0f6341c0:8990:5)
    at HTMLDocument.<anonymous> (livewire.js?id=0f6341c0:10449:17)
```

**Comment by danharrin** [comment]
I can't reproduce this bug using your reproduction repository @theMelfix. The model and migration wasn't added, so I added that myself, and I visited the list page, and there were no console errors.

Your issue description seems AI generated. It says that `Livewire.interceptMessage()` doesn't exist, when it definitely does. It's mentioned in the Livewire 3-4 upgrade guide as a new method: https://livewire.laravel.com/docs/4.x/upgrading#migrating-from-commit-hook

If there is some other reason why `Livewire.interceptMessage()` is not available at the point that the page loads, that is viable, but the method definitely exists.

Please submit a new reproduction repository or provide more detailed instructions on how to reproduce using the existing repository, and we can investigate.

**Comment by ShaungBhone** [comment]
Same here on production.

**Comment by pxlrbt** [comment]
@ShaungBhone "Same here" doesn't help if the error is not reproducible. If this only happens in production it sounds like your serving old assets.

**Comment by ShaungBhone** [comment]
@pxlrbt 
I'm sorry if my response came across as dismissive.

I forgot to update my assets.

**Comment by pxlrbt** [comment]
@ShaungBhone It didn't come across dismissive. But a "Same Here" doesn't help much without further information. Glade you got it solved.

**Comment by Capevace** [comment]
Just leaving this here: we faced this error too and we figured out it was because we had a static `public/livewire/livewire.min.js` script (cause we've had some issues with it in the past).

This obviously took precedence over the updated Livewire v4 script from the package.
Removing `public/livewire/livewire.min.js` solved the issue for us.

**Comment by we-pe** [comment]
@Capevace Nice, i delete `public/vendor/livewire` folder then republish livewire assets with `php artisan livewire:publish --assets`
